CREATE TABLE CLIENTE
(
	CPF       VARCHAR(14)  NOT NULL PRIMARY KEY,
	NOME      VARCHAR(50)  NOT NULL,
	EMAIL     VARCHAR(90)  NOT NULL,
	ENDERECO  VARCHAR(60)  NOT NULL
);

CREATE TABLE TELEFONE_CLIENTE
(
	CPF       VARCHAR(14)  NOT NULL,
	TELEFONE  VARCHAR(15)  NOT NULL,

	CONSTRAINT TELEFONE_CLIENTE_PK PRIMARY KEY (CPF, TELEFONE),
	CONSTRAINT TELEFONE_CLIENTE_FK FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF)									
);

CREATE TABLE DISTRIBUIDORA
(
	CNPJ      VARCHAR(25)  NOT NULL,
	ENDERECO  VARCHAR(60)  NOT NULL,
	NOME      VARCHAR(50)  NOT NULL,

	CONSTRAINT DISTRIBUIDORA_PK PRIMARY KEY (CNPJ)
										
);



CREATE TABLE TELEFONE_DISTRIBUIDORA
(
	CNPJ      VARCHAR(25)  NOT NULL REFERENCES DISTRIBUIDORA(CNPJ),
	TELEFONE  VARCHAR(15)  NOT NULL,

	CONSTRAINT TELEFONE_DISTRIBUIDORA_PK PRIMARY KEY (CNPJ, TELEFONE)
										
);

CREATE TABLE FUNCIONARIO
(
	CPF      VARCHAR(14) NOT NULL,
	NOME     VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(60) NOT NULL,
	EMAIL    VARCHAR(90) NOT NULL,

	CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (CPF)
);

CREATE TABLE TELEFONE_FUNCIONARIO
(
	CPF		 VARCHAR(14) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,

	CONSTRAINT TELEFONE_FUNCIONARIO_PK PRIMARY KEY(CPF, TELEFONE),
	CONSTRAINT TELEFONE_FUNCIONARIO_FK FOREIGN KEY(CPF) REFERENCES FUNCIONARIO(CPF)
);



CREATE TABLE JOGO
(
	IDJOGO            VARCHAR(10)   NOT NULL,
	NOMEJOGO          VARCHAR(100)   NOT NULL,
	DESCRICAO         VARCHAR(800)  NOT NULL,
	VALORVENDA        NUMERIC(6,2)  NOT NULL,
	DESCONTO          NUMERIC(4,2)  NOT NULL,
	FAIXAETARIA       VARCHAR(5)    NOT NULL,
	VALORENCOMENDA    NUMERIC(10,4) NOT NULL,
	DATAENTREGA       DATE          NOT NULL,
	DATAENCOMENDA     DATE          NOT NULL,
	CODIGOENCOMENDA   VARCHAR(10)   NOT NULL,
	CNPJDISTRIBUIDORA VARCHAR(25)   NOT NULL,
	CPFFUNCIONARIO    VARCHAR(14)   NOT NULL,

	CONSTRAINT JOGO_PK PRIMARY KEY(IDJOGO),
	CONSTRAINT JOGO_DISTRIBUIDORA_FK FOREIGN KEY (CNPJDISTRIBUIDORA) REFERENCES DISTRIBUIDORA(CNPJ),
	CONSTRAINT JOGO_FUNCIONARIO_FK FOREIGN KEY (CPFFUNCIONARIO) REFERENCES FUNCIONARIO(CPF)
	
);


CREATE TABLE COMPRA
(
	CPFCLIENTE VARCHAR(14) NOT NULL,
	IDJOGO     VARCHAR(10) NOT NULL,
	DATACOMPRA DATE NOT NULL,

	CONSTRAINT COMPRA_PK PRIMARY KEY (IDJOGO),
	CONSTRAINT COMPRA_JOGO_FK FOREIGN KEY (IDJOGO) REFERENCES JOGO(IDJOGO),	
	CONSTRAINT COMPRA_CLIENTE_FK FOREIGN KEY (CPFCLIENTE) REFERENCES CLIENTE(CPF)
);
